title: "Haonan Zhang"
author: "Haonan Zhang"
description: "Haonan Zhang"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "AboutMe.html", title: "About Me", icon: arrow-right}
  - {file: 'PubList.md', title: "Research", icon: arrow-right}
  - {file: 'CV_web.html', title: "CV", icon: arrow-right}
  - {file: "index.html", title: "Data Visualization", icon: arrow-right}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hzhang96@uw.edu"}
  - {title: Github, icon: github, url: "https://github.com/haonanzhang-vv"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/haonanzhang1996/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
